use std::collections::{HashSet, VecDeque};
use uuid::Uuid;

use crate::model::graph::DialogueGraph;
use crate::model::node::NodeType;

use super::flatten::flatten_subgraphs;
use super::json_export_helpers::{build_connection_map, compare_op_str};

/// Export a dialogue graph as Markdown (.md) document.
pub fn export_markdown(graph: &DialogueGraph, name: &str) -> String {
    let flat = flatten_subgraphs(graph);
    let conn_map = build_connection_map(&flat);

    let mut out = String::new();
    out.push_str(&format!("# {name}\n\n"));
    out.push_str("*Generated by TaleNode*\n\n");

    // Characters table
    if !flat.characters.is_empty() {
        out.push_str("## Characters\n\n");
        out.push_str("| Name | Color |\n|------|-------|\n");
        for ch in &flat.characters {
            out.push_str(&format!(
                "| {} | #{:02X}{:02X}{:02X} |\n",
                ch.name, ch.color[0], ch.color[1], ch.color[2]
            ));
        }
        out.push('\n');
    }

    // Variables table
    if !flat.variables.is_empty() {
        out.push_str("## Variables\n\n");
        out.push_str("| Name | Type | Default |\n|------|------|---------|\n");
        for v in &flat.variables {
            out.push_str(&format!(
                "| {} | {:?} | {} |\n",
                v.name, v.var_type, format_value_md(&v.default_value)
            ));
        }
        out.push('\n');
    }

    // Quests
    if !flat.quests.is_empty() {
        out.push_str("## Quests\n\n");
        for q in &flat.quests {
            out.push_str(&format!("### {}\n\n", q.name));
            if !q.description.is_empty() {
                out.push_str(&format!("{}\n\n", q.description));
            }
            for obj in &q.objectives {
                let marker = if obj.optional { "- [ ] *(optional)* " } else { "- [ ] " };
                out.push_str(&format!("{}{}\n", marker, obj.text));
            }
            out.push('\n');
        }
    }

    // Dialogue flow
    out.push_str("## Dialogue Flow\n\n");
    build_dialogue_section_md(&flat, &conn_map, &mut out);

    out
}

/// Export a dialogue graph as RTF (.rtf) document.
pub fn export_rtf(graph: &DialogueGraph, name: &str) -> String {
    let flat = flatten_subgraphs(graph);
    let conn_map = build_connection_map(&flat);

    let mut body = String::new();

    // Title
    body.push_str(&rtf_para(&format!("\\b\\fs36 {name}\\b0\\fs24")));
    body.push_str(&rtf_para("Generated by TaleNode"));
    body.push_str("\\par\n");

    // Characters
    if !flat.characters.is_empty() {
        body.push_str(&rtf_para("\\b\\fs28 Characters\\b0\\fs24"));
        for ch in &flat.characters {
            body.push_str(&rtf_para(&format!(
                "  {} (#{:02X}{:02X}{:02X})",
                rtf_escape(&ch.name), ch.color[0], ch.color[1], ch.color[2]
            )));
        }
        body.push_str("\\par\n");
    }

    // Variables
    if !flat.variables.is_empty() {
        body.push_str(&rtf_para("\\b\\fs28 Variables\\b0\\fs24"));
        for v in &flat.variables {
            body.push_str(&rtf_para(&format!(
                "  {} ({:?}) = {}",
                rtf_escape(&v.name), v.var_type, format_value_md(&v.default_value)
            )));
        }
        body.push_str("\\par\n");
    }

    // Dialogue flow
    body.push_str(&rtf_para("\\b\\fs28 Dialogue Flow\\b0\\fs24"));
    build_dialogue_section_rtf(&flat, &conn_map, &mut body);

    format!("{{\\rtf1\\ansi\\deff0\n{body}}}")
}

fn build_dialogue_section_md(graph: &DialogueGraph, conn_map: &std::collections::HashMap<Uuid, Uuid>, out: &mut String) {
    let Some(start_id) = find_start(graph) else {
        out.push_str("*(No Start node found)*\n");
        return;
    };

    let mut visited = HashSet::new();
    let mut queue = VecDeque::new();
    queue.push_back(start_id);
    visited.insert(start_id);

    while let Some(node_id) = queue.pop_front() {
        let Some(node) = graph.nodes.get(&node_id) else { continue };
        match &node.node_type {
            NodeType::Start => enqueue_outputs(node, conn_map, &mut visited, &mut queue),
            NodeType::Dialogue(d) => {
                let speaker = if d.speaker_name.is_empty() { "Narrator" } else { &d.speaker_name };
                out.push_str(&format!("**{}**", speaker));
                if !d.emotion.is_empty() && d.emotion != "neutral" {
                    out.push_str(&format!(" *({})*", d.emotion));
                }
                out.push('\n');
                for line in d.text.lines() {
                    out.push_str(&format!("> {line}\n"));
                }
                out.push('\n');
                enqueue_outputs(node, conn_map, &mut visited, &mut queue);
            }
            NodeType::Choice(d) => {
                if !d.prompt.is_empty() {
                    out.push_str(&format!("**Choice:** {}\n\n", d.prompt));
                }
                for (i, choice) in d.choices.iter().enumerate() {
                    out.push_str(&format!("- {}\n", choice.text));
                    if let Some(port) = node.outputs.get(i) {
                        if let Some(&target) = conn_map.get(&port.id.0) {
                            if visited.insert(target) { queue.push_back(target); }
                        }
                    }
                }
                out.push('\n');
            }
            NodeType::Condition(d) => {
                out.push_str(&format!("*[Condition: {} {} {}]*\n\n",
                    d.variable_name, compare_op_str(d.operator), format_value_md(&d.value)));
                enqueue_all_outputs(node, conn_map, &mut visited, &mut queue);
            }
            NodeType::Event(d) => {
                for a in &d.actions {
                    out.push_str(&format!("*[Event: {} = {}]*\n", a.key, format_value_md(&a.value)));
                }
                out.push('\n');
                enqueue_outputs(node, conn_map, &mut visited, &mut queue);
            }
            NodeType::Random(d) => {
                out.push_str("*[Random]*\n");
                for (i, branch) in d.branches.iter().enumerate() {
                    out.push_str(&format!("- {:.0}%\n", branch.weight * 100.0));
                    if let Some(port) = node.outputs.get(i) {
                        if let Some(&target) = conn_map.get(&port.id.0) {
                            if visited.insert(target) { queue.push_back(target); }
                        }
                    }
                }
                out.push('\n');
            }
            NodeType::End(d) => {
                if d.tag.is_empty() {
                    out.push_str("---\n\n");
                } else {
                    out.push_str(&format!("--- *[End: {}]*\n\n", d.tag));
                }
            }
            NodeType::SubGraph(_) => enqueue_outputs(node, conn_map, &mut visited, &mut queue),
        }
    }
}

fn build_dialogue_section_rtf(graph: &DialogueGraph, conn_map: &std::collections::HashMap<Uuid, Uuid>, body: &mut String) {
    let Some(start_id) = find_start(graph) else {
        body.push_str(&rtf_para("(No Start node found)"));
        return;
    };

    let mut visited = HashSet::new();
    let mut queue = VecDeque::new();
    queue.push_back(start_id);
    visited.insert(start_id);

    while let Some(node_id) = queue.pop_front() {
        let Some(node) = graph.nodes.get(&node_id) else { continue };
        match &node.node_type {
            NodeType::Start => enqueue_outputs(node, conn_map, &mut visited, &mut queue),
            NodeType::Dialogue(d) => {
                let speaker = if d.speaker_name.is_empty() { "Narrator" } else { &d.speaker_name };
                body.push_str(&rtf_para(&format!("\\b {}\\b0 : {}", rtf_escape(speaker), rtf_escape(&d.text))));
                enqueue_outputs(node, conn_map, &mut visited, &mut queue);
            }
            NodeType::Choice(d) => {
                for choice in &d.choices {
                    body.push_str(&rtf_para(&format!("  > {}", rtf_escape(&choice.text))));
                }
                enqueue_all_outputs(node, conn_map, &mut visited, &mut queue);
            }
            NodeType::End(d) => {
                let tag = if d.tag.is_empty() { "END" } else { &d.tag };
                body.push_str(&rtf_para(&format!("--- [{}] ---", rtf_escape(tag))));
            }
            _ => enqueue_all_outputs(node, conn_map, &mut visited, &mut queue),
        }
    }
}

fn find_start(graph: &DialogueGraph) -> Option<Uuid> {
    graph.nodes.values()
        .find(|n| matches!(n.node_type, NodeType::Start))
        .map(|n| n.id)
}

fn enqueue_outputs(
    node: &crate::model::node::Node, conn_map: &std::collections::HashMap<Uuid, Uuid>,
    visited: &mut HashSet<Uuid>, queue: &mut VecDeque<Uuid>,
) {
    if let Some(port) = node.outputs.first() {
        if let Some(&target) = conn_map.get(&port.id.0) {
            if visited.insert(target) { queue.push_back(target); }
        }
    }
}

fn enqueue_all_outputs(
    node: &crate::model::node::Node, conn_map: &std::collections::HashMap<Uuid, Uuid>,
    visited: &mut HashSet<Uuid>, queue: &mut VecDeque<Uuid>,
) {
    for port in &node.outputs {
        if let Some(&target) = conn_map.get(&port.id.0) {
            if visited.insert(target) { queue.push_back(target); }
        }
    }
}

fn format_value_md(val: &crate::model::node::VariableValue) -> String {
    use crate::model::node::VariableValue;
    match val {
        VariableValue::Bool(b) => b.to_string(),
        VariableValue::Int(i) => i.to_string(),
        VariableValue::Float(f) => format!("{f:.2}"),
        VariableValue::Text(s) => format!("\"{s}\""),
    }
}

fn rtf_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('{', "\\{").replace('}', "\\}")
}

fn rtf_para(text: &str) -> String {
    format!("{{\\pard {text}\\par}}\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::node::Node;

    #[test]
    fn markdown_has_title() {
        let graph = DialogueGraph::new();
        let md = export_markdown(&graph, "My Story");
        assert!(md.contains("# My Story"));
        assert!(md.contains("Generated by TaleNode"));
    }

    #[test]
    fn markdown_dialogue_flow() {
        let mut graph = DialogueGraph::new();
        let start = Node::new_start([0.0, 0.0]);
        let s_id = start.id;
        let s_out = start.outputs[0].id;
        let mut dlg = Node::new_dialogue([0.0, 200.0]);
        if let NodeType::Dialogue(ref mut d) = dlg.node_type {
            d.speaker_name = "Guard".to_string();
            d.text = "Halt!".to_string();
        }
        let d_id = dlg.id;
        let d_in = dlg.inputs[0].id;
        graph.add_node(start);
        graph.add_node(dlg);
        graph.add_connection(s_id, s_out, d_id, d_in);

        let md = export_markdown(&graph, "Test");
        assert!(md.contains("**Guard**"));
        assert!(md.contains("> Halt!"));
    }

    #[test]
    fn rtf_has_structure() {
        let graph = DialogueGraph::new();
        let rtf = export_rtf(&graph, "Story");
        assert!(rtf.starts_with("{\\rtf1"));
        assert!(rtf.contains("Story"));
        assert!(rtf.ends_with('}'));
    }

    #[test]
    fn markdown_empty_graph() {
        let graph = DialogueGraph::new();
        let md = export_markdown(&graph, "Empty");
        assert!(md.contains("No Start node found"));
    }

    #[test]
    fn rtf_escapes_special_chars() {
        let escaped = rtf_escape("test\\{brace}");
        assert_eq!(escaped, "test\\\\\\{brace\\}");
    }
}
