use std::collections::{HashMap, HashSet, VecDeque};
use uuid::Uuid;

use crate::model::graph::DialogueGraph;
use crate::model::node::NodeType;

use super::flatten::flatten_subgraphs;
use super::json_export_helpers::{build_connection_map, build_id_map, compare_op_str};

/// Export a dialogue graph as a formatted screenplay/script document.
/// Uses Fountain-inspired plain text format for voice directors and actors.
pub fn export_screenplay(graph: &DialogueGraph, name: &str) -> String {
    let flat = flatten_subgraphs(graph);
    let id_map = build_id_map(&flat);
    let conn_map = build_connection_map(&flat);
    let _char_map = build_character_name_map(&flat);

    let mut out = String::new();

    // Header
    out.push_str(&format!("TITLE: {name}\n"));
    out.push_str("DRAFT: Generated by TaleNode\n");
    out.push_str("\n===\n\n");

    // BFS traversal from Start node
    let start_id = flat
        .nodes
        .values()
        .find(|n| matches!(n.node_type, NodeType::Start))
        .map(|n| n.id);

    let Some(start_id) = start_id else {
        out.push_str("(No Start node found)\n");
        return out;
    };

    let mut visited: HashSet<Uuid> = HashSet::new();
    let mut queue: VecDeque<Uuid> = VecDeque::new();
    queue.push_back(start_id);
    visited.insert(start_id);

    while let Some(node_id) = queue.pop_front() {
        let Some(node) = flat.nodes.get(&node_id) else {
            continue;
        };

        match &node.node_type {
            NodeType::Start => {
                // Skip start node display, just follow output
                enqueue_outputs(node, &conn_map, &mut visited, &mut queue);
            }
            NodeType::Dialogue(data) => {
                let speaker = if data.speaker_name.is_empty() {
                    "NARRATOR"
                } else {
                    &data.speaker_name
                };
                let speaker_upper = speaker.to_uppercase();

                // Character name (centered by convention — indented)
                if data.emotion.is_empty() || data.emotion == "neutral" {
                    out.push_str(&format!("    {speaker_upper}\n"));
                } else {
                    out.push_str(&format!("    {speaker_upper} ({})\n", data.emotion));
                }

                // Dialogue text (indented less)
                for line in data.text.lines() {
                    out.push_str(&format!("  {line}\n"));
                }
                out.push('\n');

                enqueue_outputs(node, &conn_map, &mut visited, &mut queue);
            }
            NodeType::Choice(data) => {
                if !data.prompt.is_empty() {
                    out.push_str(&format!("  [CHOICE: {}]\n", data.prompt));
                } else {
                    out.push_str("  [CHOICE]\n");
                }
                for (i, choice) in data.choices.iter().enumerate() {
                    out.push_str(&format!("  > {}\n", choice.text));
                    // Follow each choice branch
                    if let Some(port) = node.outputs.get(i) {
                        if let Some(&target) = conn_map.get(&port.id.0) {
                            if visited.insert(target) {
                                queue.push_back(target);
                            }
                        }
                    }
                }
                out.push('\n');
            }
            NodeType::Condition(data) => {
                let op = compare_op_str(data.operator);
                let val = format_value(&data.value);
                out.push_str(&format!(
                    "  [CONDITION: {} {op} {val}]\n",
                    data.variable_name
                ));

                // Follow both branches
                for (i, label) in ["True", "False"].iter().enumerate() {
                    if let Some(port) = node.outputs.get(i) {
                        if let Some(&target) = conn_map.get(&port.id.0) {
                            let target_label = id_map
                                .get(&target)
                                .cloned()
                                .unwrap_or_else(|| "?".to_string());
                            out.push_str(&format!("    {label} -> {target_label}\n"));
                            if visited.insert(target) {
                                queue.push_back(target);
                            }
                        }
                    }
                }
                out.push('\n');
            }
            NodeType::Event(data) => {
                for action in &data.actions {
                    let val = format_value(&action.value);
                    out.push_str(&format!(
                        "  [EVENT: {} = {val}]\n",
                        action.key
                    ));
                }
                out.push('\n');
                enqueue_outputs(node, &conn_map, &mut visited, &mut queue);
            }
            NodeType::Random(data) => {
                out.push_str("  [RANDOM]\n");
                for (i, branch) in data.branches.iter().enumerate() {
                    let pct = (branch.weight * 100.0) as i32;
                    if let Some(port) = node.outputs.get(i) {
                        if let Some(&target) = conn_map.get(&port.id.0) {
                            let target_label = id_map
                                .get(&target)
                                .cloned()
                                .unwrap_or_else(|| "?".to_string());
                            out.push_str(&format!(
                                "    {pct}% -> {target_label}\n"
                            ));
                            if visited.insert(target) {
                                queue.push_back(target);
                            }
                        }
                    }
                }
                out.push('\n');
            }
            NodeType::End(data) => {
                if data.tag.is_empty() {
                    out.push_str("  [END]\n\n");
                } else {
                    out.push_str(&format!("  [END: {}]\n\n", data.tag));
                }
                out.push_str("===\n\n");
            }
            NodeType::SubGraph(_) => {
                // Should not appear after flattening
                enqueue_outputs(node, &conn_map, &mut visited, &mut queue);
            }
        }
    }

    // Character list at end
    if !flat.characters.is_empty() {
        out.push_str("===\n\n");
        out.push_str("CHARACTERS:\n");
        for ch in &flat.characters {
            out.push_str(&format!("  - {}\n", ch.name));
        }
    }

    out.push_str("\nEND\n");
    out
}

fn enqueue_outputs(
    node: &crate::model::node::Node,
    conn_map: &HashMap<Uuid, Uuid>,
    visited: &mut HashSet<Uuid>,
    queue: &mut VecDeque<Uuid>,
) {
    for port in &node.outputs {
        if let Some(&target) = conn_map.get(&port.id.0) {
            if visited.insert(target) {
                queue.push_back(target);
            }
        }
    }
}

fn build_character_name_map(graph: &DialogueGraph) -> HashMap<Uuid, String> {
    graph
        .characters
        .iter()
        .map(|ch| (ch.id, ch.name.clone()))
        .collect()
}

fn format_value(val: &crate::model::node::VariableValue) -> String {
    use crate::model::node::VariableValue;
    match val {
        VariableValue::Bool(b) => b.to_string(),
        VariableValue::Int(i) => i.to_string(),
        VariableValue::Float(f) => format!("{f:.2}"),
        VariableValue::Text(s) => format!("\"{s}\""),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::node::Node;

    #[test]
    fn screenplay_has_header() {
        let graph = DialogueGraph::new();
        let output = export_screenplay(&graph, "Test Dialogue");
        assert!(output.contains("TITLE: Test Dialogue"));
        assert!(output.contains("DRAFT: Generated by TaleNode"));
    }

    #[test]
    fn screenplay_dialogue_formatting() {
        let mut graph = DialogueGraph::new();
        let start = Node::new_start([0.0, 0.0]);
        let s_id = start.id;
        let s_out = start.outputs[0].id;

        let mut dlg = Node::new_dialogue([0.0, 200.0]);
        if let NodeType::Dialogue(ref mut data) = dlg.node_type {
            data.speaker_name = "Guard".to_string();
            data.text = "Halt! Who goes there?".to_string();
            data.emotion = "angry".to_string();
        }
        let d_id = dlg.id;
        let d_in = dlg.inputs[0].id;

        graph.add_node(start);
        graph.add_node(dlg);
        graph.add_connection(s_id, s_out, d_id, d_in);

        let output = export_screenplay(&graph, "Test");
        assert!(output.contains("GUARD (angry)"));
        assert!(output.contains("Halt! Who goes there?"));
    }

    #[test]
    fn screenplay_choice_formatting() {
        let mut graph = DialogueGraph::new();
        let start = Node::new_start([0.0, 0.0]);
        let s_id = start.id;
        let s_out = start.outputs[0].id;

        let choice = Node::new_choice([0.0, 200.0]);
        let c_id = choice.id;
        let c_in = choice.inputs[0].id;

        graph.add_node(start);
        graph.add_node(choice);
        graph.add_connection(s_id, s_out, c_id, c_in);

        let output = export_screenplay(&graph, "Test");
        assert!(output.contains("[CHOICE]"));
        assert!(output.contains("> Option 1"));
        assert!(output.contains("> Option 2"));
    }

    #[test]
    fn screenplay_end_formatting() {
        let mut graph = DialogueGraph::new();
        let start = Node::new_start([0.0, 0.0]);
        let s_id = start.id;
        let s_out = start.outputs[0].id;

        let end = Node::new_end([0.0, 200.0]);
        let e_id = end.id;
        let e_in = end.inputs[0].id;

        graph.add_node(start);
        graph.add_node(end);
        graph.add_connection(s_id, s_out, e_id, e_in);

        let output = export_screenplay(&graph, "Test");
        assert!(output.contains("[END]"));
        assert!(output.contains("END"));
    }

    #[test]
    fn screenplay_empty_graph() {
        let graph = DialogueGraph::new();
        let output = export_screenplay(&graph, "Empty");
        assert!(output.contains("No Start node found"));
    }
}
